services:
  ranking-wca-db:
    build:
      dockerfile: ./docker/db.Dockerfile
    env_file:
      - .env
    ports:
      - "3306:3306"
    # healthcheck:
    #   test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
    #   interval: 5s
    #   timeout: 5s
    #   retries: 30
    volumes:
      - db-data:/var/lib/mysql
    # networks:
    #   - internal
    restart: unless-stopped

  ranking-wca-updater:
    build:
      dockerfile: ./docker/updater.Dockerfile
    volumes:
      - ./config.toml:/config.toml
    profiles:
      - tools
  
  ranking-wca-server:
    build:
      dockerfile: ./docker/server.Dockerfile
    volumes:
      - ./config.toml:/config.toml

volumes:
  db-data:
