services:
  ranking-wca-db:
    build: ./db
    env_file:
      - .env
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    # healthcheck:
    #   test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
    #   interval: 5s
    #   timeout: 5s
    #   retries: 30
    volumes:
      - db-data:/var/lib/mysql
    # networks:
    #   - internal
    restart: unless-stopped

# networks:
#   internal:
#     external: true

volumes:
  db-data:
