services:
  ranking-wca-db:
    build:
      dockerfile: ./docker/db.Dockerfile
    env_file:
      - db/.env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 30
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal
    restart: unless-stopped

  ranking-wca-updater:
    build:
      dockerfile: ./docker/updater.Dockerfile
    volumes:
      - ./config.toml:/config.toml
    profiles:
      - tools
    networks:
      - internal
  
  ranking-wca-server:
    build:
      dockerfile: ./docker/server.Dockerfile
    volumes:
      - ./config.toml:/config.toml
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      ranking-wca-db:
        condition: service_healthy

  ranking-wca-front:
    build:
      dockerfile: ./docker/front.Dockerfile
    ports:
      - "5173:5173"
    networks:
      - internal

volumes:
  db-data:

networks:
  internal:
    external: true