[mysql]
host = "ranking-wca-db"
# host = "127.0.0.1"
port = 3306
user = "my-db-user"
password = "my-db-password"

[mysql.tables]
default = "app"
dump = "dump"

[wca]
export_url = "https://www.worldcubeassociation.org/api/v0/export/public"

[auth]
client_id = "some-wca-client-id"
client_secret = "some-wca-client-secret"
# redirect_uri = "https://ranking.leinadium.dev/api/auth/callback"
redirect_uri = "http://localhost:8080/api/auth/callback"
