export const EVENT_NAMES = {
    '222': ['Cubo 2x2x2', 'event-333'],
    '333': ['Cubo 3x3x3', 'event-333'],
    '333bf': ['3x3x3 Vendado', 'event-333bf'],
    '333fm': ['3x3x3 Menos Movimentos', 'event-333fm'],
    '333ft': ['3x3x3 com os Pés', 'event-333ft'],
    '333mbf': ['3x3x3 Múltiplos Cubos Vendados', 'event-333mbf'],
    '333oh': ['3x3x3 com uma Mão', 'event-333oh'],
    '444': ['Cubo 4x4x4', 'event-444'],
    '444bf': ['4x4x4 Vendado', 'event-444bf'],
    '555': ['Cubo 5x5x5', 'event-555'],
    '555bf': ['5x5x5 Vendado', 'event-555bf'],
    '666': ['Cubo 6x6x6', 'event-666'],
    '777': ['Cubo 7x7x7', 'event-777'],
    clock: ['Clock', 'event-clock'],
    minx: ['Megaminx', 'event-minx'],
    pyra: ['Pyraminx', 'event-pyram'],
    skewb: ['Skewb', 'event-skewb'],
    sq1: ['Square-1', 'event-sq1']
};

export const STATE_NAMES = {
    "AC": "Acre",
    "AL": "Alagoas",
    "AP": "Amapá",
    "AM": "Amazonas",
    "BA": "Bahia",
    "CE": "Ceará",
    "DF": "Distrito Federal",
    "ES": "Espírito Santo",
    "GO": "Goiás",
    "MA": "Maranhão",
    "MT": "Mato Grosso",
    "MS": "Mato Grosso do Sul",
    "MG": "Minas Gerais",
    "PA": "Pará",
    "PB": "Paraíba",
    "PR": "Paraná",
    "PE": "Pernambuco",
    "PI": "Piauí",
    "RJ": "Rio de Janeiro",
    "RN": "Rio Grande do Norte",
    "RS": "Rio Grande do Sul",
    "RO": "Rondônia",
    "RR": "Roraima",
    "SC": "Santa Catarina",
    "SP": "São Paulo",
    "SE": "Sergipe",
    "TO": "Tocantins"
}
